server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  data:
    mongodb:
      uri: mongodb+srv://nejmimouhsine:Movie_planet1@cluster0.jwlkj3k.mongodb.net/project-management?retryWrites=true&w=majorit
      database: projectmanagement
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations