version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-spring
    environment:
      POSTGRES_DB: projectmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: