eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: authentication
  data:
    mongodb:
      uri: mongodb+srv://nejmimouhsine:0WXlW1w0WK3sstGJ@cluster0.jwlkj3k.mongodb.net/projectmanagement?retryWrites=true&w=majorit
      database: projectmanagement

application:
  config:
    authentication-url: http://localhost:8222/api/v1/auth